title: Tristan McKinnon's Digital Portfolio
email: tristan@tlmckconsulting.com
description: >-
  This is the digital portfolio of Tristan McKinnon, a data engineer and data educator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tr9800a.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Exclude the Gemfile, node_modules, and design docs from being processed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - docs

# Custom CSS and JS
sass:
  style: compressed
  sass_dir: _sass
  css_dir: assets/css
  load_paths:
    - _sass

collections:
  projects:
    output: false
  talks:
    output: false